# Generated by Django 5.0.4 on 2024-05-12 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comuna', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_inmueble', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_user', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Inmuebles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_inmueble', models.TextField()),
                ('descripcion', models.CharField(max_length=200)),
                ('terreno_construido', models.FloatField()),
                ('terreno', models.FloatField()),
                ('numero_estacionamientos', models.PositiveIntegerField(default=0)),
                ('numero_banos', models.PositiveIntegerField(default=0)),
                ('numero_habitaciones', models.PositiveIntegerField(default=0)),
                ('direccion', models.CharField(max_length=200)),
                ('precio_mensual', models.PositiveIntegerField()),
                ('estado', models.BooleanField(default=False)),
                ('id_comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.comuna')),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.region')),
                ('id_tipo_inmueble', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tipoinmueble')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=12)),
                ('correo', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_tipo_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tipouser')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
